---
### Live profile
spring:
  profiles: live
  application:
    name: transaction-manager
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name.transaction-manager}
    username: ${spring.datasource.username.transaction-manager}
    password: ${spring.datasource.password.transaction-manager}
    url: ${spring.datasource.url.transaction-manager}