
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - configs/universal/dbs/common/pockets/one-to-many
            - configs/universal/dbs/retail
            - configs/universal/cxs
            - configs/universal/common
