
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - configs/usa/dbs/common/pockets/one-to-one
            - configs/usa/dbs/retail
            - configs/usa/cxs
            - configs/usa/common
