
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - configs/combined/dbs/business-banking
            - configs/usa/iam/business-banking
            - configs/usa/common
