spring:
  profiles: live
  application:
    name: notifications-service
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.notifications-service}
    password: ${spring.datasource.password.notifications-service}
    url: ${spring.datasource.url.notifications-service}