/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates.
 *                  To maintain easy upgradability, do not edit this file.
 *                  To import a module in AppModule, please use app-module-imports.ts instead.
 *
 *
 *
 *
 *
 */
import { HttpClientModule, HttpClientXsrfModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule, NoopAnimationsModule } from '@angular/platform-browser/animations';
import { TemplateRegistry } from '@backbase/foundation-ang/core';
import { StepUpInterceptor } from '@backbase/identity-auth/step-up';
import { NOTIFICATIONS_BADGE_NOTIFICATIONS_BASE_PATH } from '@backbase/notifications-ang';
import { SharedUserContextInterceptor } from '@backbase/shared/feature/user-context';
import { initProviders } from '@backbase/shared/util/app-core';
import { BB_TIMEZONE_CONFIG_TOKEN } from '@backbase/ui-ang/date-timezone-transformation';
import { environment } from '../environments/environment';
import { appModuleImports } from './app-module-imports';
import { AppComponent } from './app.component';
import { APP_NOTIFICATIONS_BASE_PATH, ServicePathsModule } from './service-paths.module';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    HttpClientXsrfModule,
    environment.animation ? BrowserAnimationsModule : NoopAnimationsModule,
    ServicePathsModule,
    ...appModuleImports,
  ],
  providers: [
    TemplateRegistry,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: SharedUserContextInterceptor,
      multi: true,
    },
    {
      provide: NOTIFICATIONS_BADGE_NOTIFICATIONS_BASE_PATH,
      useExisting: APP_NOTIFICATIONS_BASE_PATH,
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: StepUpInterceptor,
      multi: true,
    },
    {
      provide: BB_TIMEZONE_CONFIG_TOKEN,
      useValue: 'Europe/Lisbon',
    },
    initProviders.pageTitles,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
