export const locators = {
  counterpartyForm: '[data-role="form-group-counterparty"]',
  batchTypeSelector: '[data-role="bb-form-card-menu-item"]',
  batchInfoTitle: '[data-role="form-group-batchInfo"] fieldset:first-child legend',
  nextButton: '[data-role="multi-payment-next"]',
  backButton: '[data-role="multi-payment-back"]',
  submitButton: '[data-role="multi-payment-submit"]',
  formErrorAlert: '[data-role="alert-title"]',
  saveTemplateModal: '.modal.show.manual-batch-save-template-modal',
  templateCancelButton: '[data-role="save-template-cancel"]',
  templateSaveButton: '[data-role="save-template-submit"] button',
  templateNameError: '[data-role="template-alert-name"]',
  openDialogBtn: '[data-role="dynamic-form-multipayment-card-counterpartyName"] div[role="button"]',
  saveAsTemplateModal: {
    nameField: '.modal.show.manual-batch-save-template-modal [data-role="input"]',
    nameCharCounter: '[data-role="char-counter-current-max"]',
  },
  transferDetails: {
    payment: '[data-role="manual-batch-payment"]',
    footer: '[data-role="payment-footer"]',
    footerTotalTransfers: '[data-role="payment-footer"] [data-role="total-transfers"]',
    footerTotalAmount: '[data-role="payment-footer"] [data-role="total-amount"]',
    paymentCloseBtn: '[data-role="close-to-account"]',
    confidentialSwitch: '[data-role="manual-confidential-switch"]',
  },
  reviewScreen: {
    headerText: '[data-role="review-screen-heading-label"]',
    debitorName: '[data-role="batch-order-account-name"]',
    confidentialLockIcon: '[data-role="batch-order-confidential"]',
    successMessage: 'bb-status-card[status="success"]',
  },
  summaryScreen: {
    headerText: '[data-role="summary-screen-heading-label"]',
    buttons: {
      manageBatches: '[data-role="go-manage-batches-button"]',
      newBatch: '[data-role="new-batch-button"]',
      saveAsTemplate: '[data-role="save-as-template-button"]',
    },
  },
  paymentsInfo: {
    tableRows: '[data-role="manual-batches-review-screenitems"]',
    tableCellName: '[data-role="review-screenitem-counterparty-name"]',
    tableCellNumber: '[data-role="review-screenitem-counterparty-number"]',
    tableCelldescription: '[data-role="review-screenitem-description"]',
    tableCellAmount: '[data-role="review-screenitem-amount"]',
  },
  fields: {
    batchName: '[data-role="dynamic-form-textbox-name"] [data-role="input"]',
    batchNameCharCounter: '[data-role="dynamic-form-textbox-name"] [data-role="char-counter-current-max"]',
    requestedExecutionDate:
      '[data-role="dynamic-form-datepicker-requestedExecutionDate"] [data-role="input-date-single"]',
    confidentialType: '[data-role="dynamic-form-switch-dropdown-confidentialType"] [data-role="checkbox-input"]',
    companyName: '[data-role="dynamic-form-textbox-companyName"] [data-role="input"]',
    companyId: '[data-role="dynamic-form-textbox-companyId"] [data-role="input"]',
    execdate: '[data-role="dynamic-form-datepicker-requestedExecutionDate"] [data-role="input-date-single"]',
    entryClass: '[data-role="dynamic-form-select-entryClass"] [data-role="dropdown"]',
    fromAccount: '[data-role="dynamic-form-account-selector-debitorAccount"] [data-role="debit-account-selector"]',
    fromAccountSelectedTitle: '[data-role="dynamic-form-account-selector-debitorAccount"] [data-role="card-title"]',
    prenote: '[data-role="dynamic-form-multipayment-card-prenote"] [data-role="checkbox-input"]',
    prenoteAllToggle: '[data-role="prenote-all-toggle"]',
    counterparty: {
      contactSearch: '[data-role="beneficiary-account-search-input"] [data-role="search-input"]',
      searchInput:
        '[data-role="dynamic-form-multipayment-card-counterpartyName"] [data-role="beneficiary-contact-search-input"]',
      menu: '[data-role="dynamic-form-multipayment-card-counterpartyName"]',
      menuButton: '[data-role="open-beneficiary-dropdown-list-button"]',
      menuItemButton: '[data-role="account-selector-menu"].show [data-role="account-selector-menu-item-button"]',
      addNewPayeeButton: '[data-role="add-new-payee-button"]',
      emptyList: '[data-role="account-selector-menu"] [data-role="empty-state-title"]',
    },
    payeeModal: {
      name: '[data-role="payee-form-name"] [data-role="input"]',
      accountNumber: '[data-role="payee-form-account-number"] [data-role="input"]',
      accountType: '[data-role="payee-account-type"] [data-role="dropdown"]',
      routingTransitNumber: '[data-role="payee-form-routing-transit-number"] [data-role="input"]',
      saveButton: '[data-role="form-modal-save-data"] button',
      selectedPayee: '[data-role="selected-to-account"]',
      dialogHeader: '[data-role="form-modal-config-header"]',
      closeDialog: '[data-role="form-modal-close-button"]',
    },
    amount: '[data-role="dynamic-form-multipayment-card-amount"] [data-role="bb-amount-input-ui"]',
  },
  addNewPaymentBtn: '[data-role="add-account-card"] [data-role="btn-icon-link-md-def"]',
  validationMessages: {
    batchName: '[data-role="dynamic-form-textbox-name"] [data-role="input-error"]',
    requestedExecutionDate: '[data-role="dynamic-form-datepicker-requestedExecutionDate"] [data-role="input-error"]',
    debitorAccount: '[data-role="dynamic-form-account-selector-debitorAccount"] [data-role="input-error"]',
    counterparty: '[data-role="form-group-counterparty"] [data-role="input-error"]',
    'counterparty.counterpartyName':
      '[data-role="dynamic-form-multipayment-card-counterpartyName"] [data-role="input-error"]',
    'counterparty.amount': '[data-role="dynamic-form-multipayment-card-amount"] [data-role="input-error"]',
    companyName: '[data-role="dynamic-form-textbox-companyName"] [data-role="input-error"]',
    companyId: '[data-role="dynamic-form-textbox-companyId"] [data-role="input-error"]',
    entryClass: '[data-role="dynamic-form-select-entryClass"] [data-role="input-error"]',
  },
  achBatchcardButton: '[data-role="bb-form-card-menu-item"]:last-child',
  fromAccountListItem: '.bb-product-item-basic-account-ui',
  closeManualBatchButton: '[data-role="close-multipayment-widget"]',
  confirmationDialog: {
    header: '[data-role="confirmation-header"] [data-role="headings"]',
    discardButton: '[data-role="multi-payment-batch-discard-button-modal"]',
    cancelButton: '[data-role="multi-payment-batch-discard-cancel-button-modal"]',
  },
  transactionSingingHeader: 'bb-transaction-signing-header',
};
