---
### Live profile
spring:
  profiles: live
  application:
    name: payment-batch
  config:
    use-legacy-processing: true
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.payment-batch}
    password: ${spring.datasource.password.payment-batch}
    url: ${spring.datasource.url.payment-batch}

backbase:
  communication:
    services:
      dbs:
        integration:
          external:
            outbound:
              paymentorder:
                batch:
                  service-id: payment-batch-core-mock